export interface Post {
    id: string,
    name: string,
    wifi: number,
    seat: number,
    quiet: number,
    tasty: number,
    cheap: number,
    music: number,
    address: string,
    latitude: string,
    longitude: string,
    url: string,
    limited_time: string,
    socket: string,
    standing_desk: string,
    mrt: string,
    open_time: string,
    remark: string,
}
